### ISSUE TITLE
GUI implementatie ideeen

### ISSUE THREAD

**Issue by Borrelhapje** [Borrelhapje/design-for-change#13]
Gebruik een visitor of chain of responsibility voor de verschillende Content render stappen, waarschijnlijk is een Visitor pattern het handigst zodat we redelijk makkelijk nieuwe types Content erbij kunnen doen. Chain of responsibility is ook een mogelijkheid maar omdat het renderen waarschijnlijk anders zal zijn obv eerdere keuzes (bv indentation van lists obv hoe diep de list genest is) die onthouden moeten worden is een single Visitor instance dan veel handiger.

Voor de verschillende acties die in de GUI zitten lijkt een Facade wel handig, waar dan voorlopig de volgende methodes in zitten:
 - start(SlideShow show)
 - stop()
 - nextSlide()
 - previousSlide()

**Comment by Borrelhapje** [comment]
Visitor pattern werkt hier fantastisch goed in combinatie met swing, renderen van Content is best wel simpel hiermee.

**Comment by erikhorlings** [comment]
> Visitor pattern werkt hier fantastisch goed in combinatie met swing, renderen van Content is best wel simpel hiermee.

Zo'n vermoeden had ik al. Fijn om dat bevestigd te zien :-)
Hoe is de voortgang?

**Comment by Borrelhapje** [comment]
Zie #15
