### ISSUE TITLE
Implementatie nieuwe feature: variaties op slide volgorde

### ISSUE THREAD

**Issue by erikhorlings** [Borrelhapje/design-for-change#19]
Wat hebben we nodig voor het aangeven van meerdere slide volgordes? En hoe implementeren we dat?
In het bestand zou ik op het niveau van de slideshow een list op willen nemen met sequenties, met daarin een key, description en list of slide numbers. In elke slide moet dan ook een slide number worden opgenomen.
Voor het domeinmodel zijn er twee opties:
1) Neem de sequences op in de slide show. Bij het aanmaken van de iterator moet je dan aangeven voor welke sequence je een iterator wilt hebben.
2) Maak een overkoepelende slide show collection en maak voor elke sequence een slide show met zijn eigen set aan  slides.

Allebei zijn mogelijk, maar ik blijf erbij dat optie 1 de beste is. Ook het wegschrijven van een slide show naar een bestand is dan een stuk makkelijker. Het argument dat je dan een slide show hebt die eigenlijk uit meerdere slide shows bestaat vind ik niet helemaal kloppen. Je hebt nog steeds 1 slide show, maar met wat variaties voor verschillend publiek. Het is niet ineens een andere slide show geworden.

Mochten we ook nog willen implementeren dat we delen niet willen tonen voor bepaalde sequences, dan is dat eenvoudig te implementeren door een 'hidden' attribuut op te nemen voor alle content en dan aan de getComponent methode een parameter Sequence toevoegen die hierop controleert om te zien of er null moet worden teruggegeven of niet. Dit resoneert ook goed met optie 1. Ook doet dit me denken aan het alsnog opnemen van Slide in het Composite pattern voor Content, alhoewel ik dat niet meer daadwerkelijk wil gaan implementeren.

**Comment by Borrelhapje** [comment]
Eens, toevoegen in slide show lijkt me beter passen in het domein.

Dus toevoegen in het domein:
 - een Sequence interface, met een String key, String description en dan `Iterator<Slide>` of `Iterator<Integer>`? Ik zou voor `Iterator<Slide>` gaan, slides gaan nummeren lijkt me een implementatie detail
 - SlideShow krijgt een `Iterator<Sequence>` erbij

Verder geen changes in het domein? GUIFacade blijft ook identiek.

Eens met het niet meer implementeren van Slide in de Composite.

**Comment by Borrelhapje** [comment]
Ik heb domain en object creation gedaan, is het een idee dat jij het stukje GUI toevoegt?

**Comment by erikhorlings** [comment]
Prima, ik kijk binnenkort naar de GUI. Ik twijfel hier tussen twee opties:
1) Een apart scherm om de sequence te selecteren en daarna het huidige scherm te openen.
2) Binnen het huidige scherm een dropdown om de sequence te selecteren.

Ik geef de voorkeur aan de eerste. Anders moet je mogelijk al iets gaan tonen, voordat je een sequence hebt geselecteerd. Ook al is het alleen maar een leeg scherm, ik vind dat idee gewoon niet mooi.

**Comment by Borrelhapje** [comment]
Zit er in principe in.
