### ISSUE TITLE
Voeg action/rules/strategy stukken toe

### ISSUE THREAD

**Issue by Borrelhapje** [Borrelhapje/design-for-change#2]
We hebben slechts een paar rules: next en previous slide action rules.

Ik denk dat de meeste rules via een generiek Predicate met de relevante info kunnen werken, daar hoeven we eigenlijk niet per se een los interface of abstracte class voor te maken?

We zouden een strategy kunnen maken voor de title slide (wel/geen/gedeeltelijke meta informatie) en voor de table of contents (ook wel/niet/gedeeltelijke info).

**Comment by erikhorlings** [comment]
Denk je dat we alle rules al onderkend hebben? Waarschijnlijk wel, het is ook maar een relatief klein domein.

Het is mij nog niet duidelijk in hoeverre we klassen gaan maken voor de rules, of dat iets is dat intern voor een klasse gaat zijn. Zou kunnen dat we de rules moeten hergebruiken voor bijvoorbeeld enabled/disabled knoppen _en_ tegelijkertijd om te voorkomen dat de actie uitgevoerd wordt. Beetje overkill in dit geval, maar misschien wel wat de docenten willen zien in deze module. Dan kom je waarschijnlijk inderdaad uit op een Predicate klasse. Valt dat nog onder een design pattern te vangen?

Ik zat nog na te denken over het tonen van de meta informatie, zowel op de title slide, als op de ordinary slides. Strategy pattern zou een idee zijn, maar dat gaat er van uit dat er verschillende manieren zijn om iets te tonen. Misschien is Decorator beter, omdat je dan bepaalt of bepaalde dingen ueberhaupt getoond worden. Ik moet hier nog even over nadenken. Misschien sowieso iets om maandag over te praten.

**Comment by Borrelhapje** [comment]
We maken geen rules voor next/previous actions, aangezien die omvat worden door de iterator hasPrevious hasNext methods. Dat is informatie waar iterator over beschikt en dat ligt qua verantwoordelijkheid ook heel dicht bij iterator. Er losse classes bij maken lijkt dus niet nodig.

Start Slide show action laten we erin zitten voor toekomstige flexibiliteit (ipv bij startup een file meegeven kan er bv ook een selectie menu komen). Voorlopig kan deze na initialisatie meteen aangeroepen worden door het programma zelf.

Next/Previous slide acties houden we erin, navigeren over slides is echt een core onderdeel van het domein  van slide show presenteren.

Voor de Stop action gaan we een StopStrategy toevoegen. Initieel wordt dit een simpele System.exit(0) als implementatie maar dit lijkt een plek waar in de toekomst verandering kan komen.

**Comment by erikhorlings** [comment]
Ik heb het idee dat we nog een soort Main klasse moeten implementeren, waarin we de SlideShow moeten gaan aanmaken en waarin we dan het werk van het renderen van de slides, maar ook de start/stop acties weer delegeren naar andere klassen. Iets met een GUI interface of zoiets, waarbij de implementaties dan zelf de slide show en een slide iterator als attribuut opslaan en de next/previous slide acties uitvoeren. Ik heb alleen nog geen idee tot welke methodes dat gaat leiden. Kon wel eens iets worden dat heel specifiek in de implementatie van de GUI terecht komt als button event handler ofzo. Lastig.
