### ISSUE TITLE
Verslag

### ISSUE THREAD

**Issue by erikhorlings** [Borrelhapje/design-for-change#24]
Ik heb al een paar dingetjes in het document geplaatst (https://www.overleaf.com/project/653d24fdfd8e1c49e7470d84), maar misschien moeten we hier maar even een overzicht neerzetten van alles wat we nog moeten bespreken/aanpassen.

De basis die je hebt neergezet is volgens mij goed. Het voelt kort, maar ik zie ook niet goed waarom we meer woorden zouden moeten gebruiken, volgens mij zijn de onderdelen die zijn uitgewerkt redelijk compleet.

Dingen die ik zou willen bespreken:
- Moeten we nog aangeven waarom we aparte Meta klassen gebruiken?
- Ik heb een class diagram toegevoegd voor het domein na implementatie van de nieuwe feature. Willen we hier ook nog een diagram van voor hebben? Om te kunnen vergelijken?
- We hebben een (nu nog open) PR om FrameEntryPoint te wijzigen naar SwingGUIFacade. Ik wil die doorvoeren, uiteraard met de changes die jij hebt voorgesteld, en dan in het verslag alles beschrijven alsof dat al zo was voor de implementatie van de nieuwe feature.
- Bij 'Object creation' geeft je aan dat er iets moest veranderen, om sequences te hebben met of zonder ToC of title slide. Dat ondersteunen we op dit moment nog niet. Moeten we dat nog expliciet aangeven?
- Ik snap nog niet waarom de creatie van ToC en title slide in AbstractSlideShowFactory zit. Kun je dit misschien nog beter uitleggen? Ik had het bij de PR ook helemaal gemist en vind AbstractSlideFactory een veel logischer plaats.
- Over het gebruik van een Builder pattern: het Builder pattern zoals dit in het GoF boek wordt besproken is volgens mij een ander Builder pattern dan wat jij hier bedoelt. Hier bedoelen we eigenlijk een pattern dat gebruikt wordt om in Java te dealen met constructors die onhandig veel parameters hebben. Ik denk dat we dat nog wel moeten melden hier.

**Comment by erikhorlings** [comment]
Als het goed is, kom je vandaag weer terug uit Schotland. Welkom terug.

Ik ben vandaag druk bezig geweest met het verslag. Voornamelijk patterns beschreven. Ik heb helaas morgen nauwelijks tijd om nog bezig te zijn en zondag ook maar een deel van de dag. Zie jij nog mogelijkheid om het een en ander te doen, zodat we het verslag wel zondagavond kunnen inleveren? Ik heb nog wel een beetje tijd, maar ik denk dat we wel even goed moeten overleggen wie wat doet.

**Comment by Borrelhapje** [comment]
Ik zie nog 3 dingen die we moeten doen:
 - [x] appendix C (iets voor jou @erikhorlings ? Jij hebt de initiele setup daarvan gedaan)
 - [x] appendix D (doe ik wel want die heb ik gebouwd)
 - [x] proofreaden
 - [ ] reflection (elk individueel, dus schrijf dit mss alvast uit zodat je het achter je eigen versie van het verslag kan plakken)
